Modify aconfig for sudo usage and yay installation
Updated the aconfig script to include 'sudo' in package installation and improved user permissions handling for yay installation.

diff --git a/aconfig b/aconfig
--- a/aconfig
+++ b/aconfig
@@ -41,7 +41,7 @@ pacman-key --init
 pacman-key --populate archlinux
 pacman -Syu --noconfirm archlinux-keyring
 
-pacman -Syu --noconfirm grub os-prober nano initramfs linux linux-lts linux-lts-headers linux-headers reflector kernel-modules-hook git
+pacman -Syu --noconfirm grub os-prober nano initramfs linux linux-lts linux-lts-headers linux-headers reflector kernel-modules-hook git sudo
 
 #reflector
 reflector --verbose --ipv4 --protocol https,http --score 50 --fastest 10 --save /etc/pacman.d/mirrorlist
@@ -184,21 +184,29 @@ clear
 
 echo "Installing yay:"
 
-echo EDITOR="/usr/bin/nano" >> /etc/environment
+printf '%s\n' 'EDITOR=/usr/bin/nano' >> /etc/environment
 
-chown -R $userName:users /home/$userName
+# yay must be built as the unprivileged user, not root.
 
-cd /home/$userName
+chown -R "${userName}:users" "/home/${userName}"
 
-sudo -u $userName HOME=/home/$userName git clone https://archlinux.org
+cd "/home/${userName}"
 
-cd /home/$userName/yay
+sudo -u "${userName}" HOME="/home/${userName}" git clone --depth 1 https://aur.archlinux.org/yay.git "/home/${userName}/yay"
 
-sudo -u $userName HOME=/home/$userName makepkg -csr --skippgpcheck --noconfirm
+cd "/home/${userName}/yay"
 
-cd /home/$userName
+sudo -u "${userName}" HOME="/home/${userName}" makepkg -csr --noconfirm
 
-pacman -U --noconfirm /home/$userName/yay/yay-*.pkg.tar.zst
+# Install the package that makepkg produced.
+pacman -U --noconfirm "/home/${userName}"/yay/yay-*.pkg.tar.zst
+
+# Do not continue with the rest of aconfig if yay failed.
+if ! command -v yay >/dev/null 2>&1
+then
+      echo "ERROR: yay was not installed successfully."
+      exit 1
+fi
 
 sleep 5s
 
